### ISSUE TITLE
Range feature parity

### ISSUE THREAD

**Issue by CAD97** [CAD97/indexing#2]
<https://docs.rs/indexing/0.3/indexing/struct.Range.html>

`<_>`

- [x] `.len()`
- [x] `.is_empty()`
- [x] `.nonempty()`
- [X] `.start()` => `.start().untrusted()`
- [X] `.end()` => `.end().untrusted()`
- [X] `.split_in_half()` =>
  - Slice: `.split_in_half_raw(UnitProof)`
  - General: `.split_near_half_in(&Container)`
- [X] `.split_at(usize)` =>
  - Slice: `.split_at_raw(u32, UnitProof)`
  - General: `split_at(Index)`
- [X] `.contains(usize)` =>
  - Slice: `.contains_raw(u32, UnitProof)`
  - General: `.contains(Index)`
  - General: `.contains_in(u32, &Container)`
  - General: `.near_in(u32, &Container)`
- [ ] `.subdivide(usize)`
- [x] `.join(Range)`
- [x] `.join_cover(Range)`
- [x] `.join_cover_both(Range)`
- [X] `.as_range()` => `.untrusted()`
- [x] `.frontiers()`
- [ ] `.forward_by()`
- [ ] `.forward_range_by()`
- [X] `.no_proof()` => `.erased()`
- [X] `.first()` => `.start()`
- [X] `.upper_middle()` =>
  - Slice: `.middle_raw(UnitProof)`
  - General: `.middle_in(&Container)`
- [X] `.past_the_end()` => `.end()`

`<NonEmpty>`

- [ ] `lower_middle`
- [ ] `last`
- [ ] `tail`
- [ ] `init`
- [ ] `advance`
- [ ] `advance_by`
- [ ] `advance_back`

**Comment by CAD97** [comment]
Closing as I'm taking a different direction
